# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'miasmod_data.ui'
#
# Created: Wed Dec 18 17:31:29 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MiasmataData(object):
    def setupUi(self, MiasmataData):
        MiasmataData.setObjectName("MiasmataData")
        MiasmataData.resize(400, 300)
        self.horizontalLayout = QtGui.QHBoxLayout(MiasmataData)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeView = QtGui.QTreeView(MiasmataData)
        self.treeView.setUniformRowHeights(True)
        self.treeView.setAllColumnsShowFocus(True)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout.addWidget(self.treeView)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.edit = QtGui.QPushButton(MiasmataData)
        self.edit.setEnabled(False)
        self.edit.setObjectName("edit")
        self.verticalLayout_2.addWidget(self.edit)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(MiasmataData)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.name = QtGui.QLineEdit(MiasmataData)
        self.name.setReadOnly(True)
        self.name.setObjectName("name")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.name)
        self.type = QtGui.QComboBox(MiasmataData)
        self.type.setObjectName("type")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.type)
        self.label_2 = QtGui.QLabel(MiasmataData)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(MiasmataData)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.value_line = QtGui.QLineEdit(MiasmataData)
        self.value_line.setReadOnly(True)
        self.value_line.setObjectName("value_line")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.value_line)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.value_list = QtGui.QListWidget(MiasmataData)
        self.value_list.setObjectName("value_list")
        self.verticalLayout_2.addWidget(self.value_list)
        self.value_table = QtGui.QTableWidget(MiasmataData)
        self.value_table.setObjectName("value_table")
        self.value_table.setColumnCount(0)
        self.value_table.setRowCount(0)
        self.verticalLayout_2.addWidget(self.value_table)
        self.value_hex = QtGui.QPlainTextEdit(MiasmataData)
        self.value_hex.setReadOnly(True)
        self.value_hex.setObjectName("value_hex")
        self.verticalLayout_2.addWidget(self.value_hex)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.cancel = QtGui.QPushButton(MiasmataData)
        self.cancel.setEnabled(False)
        self.cancel.setObjectName("cancel")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.cancel)
        self.pushButton = QtGui.QPushButton(MiasmataData)
        self.pushButton.setEnabled(False)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.pushButton)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.label.setBuddy(self.name)
        self.label_2.setBuddy(self.type)

        self.retranslateUi(MiasmataData)
        QtCore.QMetaObject.connectSlotsByName(MiasmataData)

    def retranslateUi(self, MiasmataData):
        self.edit.setText(QtGui.QApplication.translate("MiasmataData", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MiasmataData", "&Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MiasmataData", "&Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MiasmataData", "Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel.setText(QtGui.QApplication.translate("MiasmataData", "&Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MiasmataData", "&Save", None, QtGui.QApplication.UnicodeUTF8))

