# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'savemanager.ui'
#
# Created: Sat Dec  7 00:42:45 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SaveManager(object):
    def setupUi(self, SaveManager):
        SaveManager.setObjectName(_fromUtf8("SaveManager"))
        SaveManager.resize(1215, 793)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(SaveManager)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.install_path = QtGui.QLineEdit(SaveManager)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.install_path.sizePolicy().hasHeightForWidth())
        self.install_path.setSizePolicy(sizePolicy)
        self.install_path.setObjectName(_fromUtf8("install_path"))
        self.gridLayout.addWidget(self.install_path, 2, 0, 1, 1)
        self.save_browse = QtGui.QPushButton(SaveManager)
        self.save_browse.setObjectName(_fromUtf8("save_browse"))
        self.gridLayout.addWidget(self.save_browse, 4, 1, 1, 1)
        self.install_browse = QtGui.QPushButton(SaveManager)
        self.install_browse.setObjectName(_fromUtf8("install_browse"))
        self.gridLayout.addWidget(self.install_browse, 2, 1, 1, 1)
        self.save_path = QtGui.QLineEdit(SaveManager)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_path.sizePolicy().hasHeightForWidth())
        self.save_path.setSizePolicy(sizePolicy)
        self.save_path.setObjectName(_fromUtf8("save_path"))
        self.gridLayout.addWidget(self.save_path, 4, 0, 1, 1)
        self.label_2 = QtGui.QLabel(SaveManager)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 2)
        self.label = QtGui.QLabel(SaveManager)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 32, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.save0 = QtGui.QPushButton(SaveManager)
        self.save0.setEnabled(False)
        self.save0.setMinimumSize(QtCore.QSize(0, 38))
        self.save0.setMaximumSize(QtCore.QSize(416, 16777215))
        self.save0.setObjectName(_fromUtf8("save0"))
        self.verticalLayout.addWidget(self.save0)
        self.save1 = QtGui.QPushButton(SaveManager)
        self.save1.setEnabled(False)
        self.save1.setMinimumSize(QtCore.QSize(0, 38))
        self.save1.setMaximumSize(QtCore.QSize(416, 16777215))
        self.save1.setObjectName(_fromUtf8("save1"))
        self.verticalLayout.addWidget(self.save1)
        self.save2 = QtGui.QPushButton(SaveManager)
        self.save2.setEnabled(False)
        self.save2.setMinimumSize(QtCore.QSize(0, 38))
        self.save2.setMaximumSize(QtCore.QSize(416, 16777215))
        self.save2.setObjectName(_fromUtf8("save2"))
        self.verticalLayout.addWidget(self.save2)
        spacerItem1 = QtGui.QSpacerItem(20, 32, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lbl_coast = QtGui.QLabel(SaveManager)
        self.lbl_coast.setEnabled(False)
        self.lbl_coast.setObjectName(_fromUtf8("lbl_coast"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_coast)
        self.show_coast = QtGui.QPushButton(SaveManager)
        self.show_coast.setEnabled(False)
        self.show_coast.setObjectName(_fromUtf8("show_coast"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.show_coast)
        spacerItem2 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.formLayout.setItem(3, QtGui.QFormLayout.SpanningRole, spacerItem2)
        self.lbl_urns = QtGui.QLabel(SaveManager)
        self.lbl_urns.setEnabled(False)
        self.lbl_urns.setObjectName(_fromUtf8("lbl_urns"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lbl_urns)
        self.urns = QtGui.QLabel(SaveManager)
        self.urns.setText(_fromUtf8(""))
        self.urns.setObjectName(_fromUtf8("urns"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.urns)
        self.show_urns = QtGui.QPushButton(SaveManager)
        self.show_urns.setEnabled(False)
        self.show_urns.setObjectName(_fromUtf8("show_urns"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.SpanningRole, self.show_urns)
        spacerItem3 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.formLayout.setItem(6, QtGui.QFormLayout.SpanningRole, spacerItem3)
        self.lbl_heads = QtGui.QLabel(SaveManager)
        self.lbl_heads.setEnabled(False)
        self.lbl_heads.setObjectName(_fromUtf8("lbl_heads"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.lbl_heads)
        self.heads = QtGui.QLabel(SaveManager)
        self.heads.setEnabled(False)
        self.heads.setObjectName(_fromUtf8("heads"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.heads)
        self.show_heads = QtGui.QPushButton(SaveManager)
        self.show_heads.setEnabled(False)
        self.show_heads.setObjectName(_fromUtf8("show_heads"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.show_heads)
        self.reset_head = QtGui.QPushButton(SaveManager)
        self.reset_head.setEnabled(False)
        self.reset_head.setObjectName(_fromUtf8("reset_head"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.reset_head)
        spacerItem4 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.formLayout.setItem(9, QtGui.QFormLayout.SpanningRole, spacerItem4)
        self.lbl_notes = QtGui.QLabel(SaveManager)
        self.lbl_notes.setEnabled(False)
        self.lbl_notes.setObjectName(_fromUtf8("lbl_notes"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.lbl_notes)
        self.notes = QtGui.QLabel(SaveManager)
        self.notes.setText(_fromUtf8(""))
        self.notes.setObjectName(_fromUtf8("notes"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.notes)
        self.reset_notezz = QtGui.QPushButton(SaveManager)
        self.reset_notezz.setEnabled(False)
        self.reset_notezz.setObjectName(_fromUtf8("reset_notezz"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.SpanningRole, self.reset_notezz)
        spacerItem5 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.formLayout.setItem(12, QtGui.QFormLayout.SpanningRole, spacerItem5)
        self.lbl_plants = QtGui.QLabel(SaveManager)
        self.lbl_plants.setEnabled(False)
        self.lbl_plants.setObjectName(_fromUtf8("lbl_plants"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.lbl_plants)
        self.plants = QtGui.QLabel(SaveManager)
        self.plants.setText(_fromUtf8(""))
        self.plants.setObjectName(_fromUtf8("plants"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.plants)
        self.coast = QtGui.QLabel(SaveManager)
        self.coast.setText(_fromUtf8(""))
        self.coast.setObjectName(_fromUtf8("coast"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.coast)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.progress = QtGui.QLabel(SaveManager)
        self.progress.setFrameShape(QtGui.QFrame.Panel)
        self.progress.setFrameShadow(QtGui.QFrame.Sunken)
        self.progress.setText(_fromUtf8(""))
        self.progress.setObjectName(_fromUtf8("progress"))
        self.verticalLayout.addWidget(self.progress)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.scrollArea = QtGui.QScrollArea(SaveManager)
        self.scrollArea.setMinimumSize(QtCore.QSize(768, 0))
        self.scrollArea.setBaseSize(QtCore.QSize(1024, 1024))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1024, 1024))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(1024, 1024))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)

        self.retranslateUi(SaveManager)
        QtCore.QMetaObject.connectSlotsByName(SaveManager)
        SaveManager.setTabOrder(self.install_path, self.install_browse)
        SaveManager.setTabOrder(self.install_browse, self.save_path)
        SaveManager.setTabOrder(self.save_path, self.save_browse)
        SaveManager.setTabOrder(self.save_browse, self.save0)
        SaveManager.setTabOrder(self.save0, self.save1)
        SaveManager.setTabOrder(self.save1, self.save2)
        SaveManager.setTabOrder(self.save2, self.show_coast)
        SaveManager.setTabOrder(self.show_coast, self.show_urns)
        SaveManager.setTabOrder(self.show_urns, self.show_heads)
        SaveManager.setTabOrder(self.show_heads, self.reset_head)
        SaveManager.setTabOrder(self.reset_head, self.reset_notezz)
        SaveManager.setTabOrder(self.reset_notezz, self.scrollArea)

    def retranslateUi(self, SaveManager):
        SaveManager.setWindowTitle(QtGui.QApplication.translate("SaveManager", "Miasmata Save Utility", None, QtGui.QApplication.UnicodeUTF8))
        self.save_browse.setText(QtGui.QApplication.translate("SaveManager", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.install_browse.setText(QtGui.QApplication.translate("SaveManager", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SaveManager", "Miasmata Saved Games Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SaveManager", "Miasmata Install Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.save0.setText(QtGui.QApplication.translate("SaveManager", "Load Save Slot 1", None, QtGui.QApplication.UnicodeUTF8))
        self.save1.setText(QtGui.QApplication.translate("SaveManager", "Load Save Slot 2", None, QtGui.QApplication.UnicodeUTF8))
        self.save2.setText(QtGui.QApplication.translate("SaveManager", "Load Save Slot 3", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_coast.setText(QtGui.QApplication.translate("SaveManager", "Coastline Mapped:", None, QtGui.QApplication.UnicodeUTF8))
        self.show_coast.setText(QtGui.QApplication.translate("SaveManager", "Show Mapped Coastline", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_urns.setText(QtGui.QApplication.translate("SaveManager", "Urns Lit:", None, QtGui.QApplication.UnicodeUTF8))
        self.show_urns.setText(QtGui.QApplication.translate("SaveManager", "Show Lit Urns", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_heads.setText(QtGui.QApplication.translate("SaveManager", "Head Statues Located:", None, QtGui.QApplication.UnicodeUTF8))
        self.heads.setText(QtGui.QApplication.translate("SaveManager", "Coming Soon!", None, QtGui.QApplication.UnicodeUTF8))
        self.show_heads.setText(QtGui.QApplication.translate("SaveManager", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_head.setText(QtGui.QApplication.translate("SaveManager", "Reset one statue...", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_notes.setText(QtGui.QApplication.translate("SaveManager", "Notes Found:", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_notezz.setText(QtGui.QApplication.translate("SaveManager", "Reset missing Sanchez #1 note...", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_plants.setText(QtGui.QApplication.translate("SaveManager", "Plants Found:", None, QtGui.QApplication.UnicodeUTF8))

